# Generated by Django 5.0.7 on 2024-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("witnesses", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
    ]
