# Generated by Django 4.2 on 2024-07-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searcher", "0002_remove_case_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="pdf",
            field=models.FileField(default="", upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="case",
            name="summary",
            field=models.TextField(default=""),
        ),
    ]
