# Generated by Django 4.2 on 2024-07-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searcher", "0003_case_pdf_case_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="pdf",
            field=models.FileField(default="", upload_to="media/pdf/"),
        ),
    ]
