# Generated by Django 4.2 on 2024-07-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searcher", "0004_alter_case_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="pdf",
            field=models.FileField(default="", upload_to="casefiles/pdf/"),
        ),
    ]
