# Generated by Django 4.2 on 2024-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("searcher", "0005_alter_case_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="location",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="type",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="witnesses",
            field=models.TextField(default=""),
        ),
    ]
