# Generated by Django 4.2 on 2024-08-01 23:05

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):
    dependencies = [
        (
            "searcher",
            "0006_alter_case_location_alter_case_title_alter_case_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="case",
            old_name="witnesses",
            new_name="interesting_points",
        ),
        migrations.RenameField(
            model_name="case",
            old_name="type",
            new_name="number_of_witnesses",
        ),
        migrations.AddField(
            model_name="case",
            name="date",
            field=models.CharField(default="xxxx-xx", max_length=255),
        ),
        migrations.AddField(
            model_name="case",
            name="sighted_object",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="case",
            name="witness_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="case",
            name="pdf",
            field=models.FileField(
                storage=storages.backends.s3.S3Storage(), upload_to=""
            ),
        ),
    ]
